app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__, template_folder='templates')

from app.main import routes, email

app/main/routes.py
from dateutil.parser import parse
from flask import render_template, request

from werkzeug.exceptions import BadRequestKeyError

from app.main import bp
from app.models import Server
from app.modules import manage_automations


@bp.route('/', methods=['GET', 'POST'])
def index():
    if request.method == 'POST':
        try:
            search_str = request.form['search']
            return search(search_str)
        except IndexError:
            search_str = ""
            return search(search_str)
    return render_template('index.html', title='Home')


@bp.route('/search')
def search(search_str):
    if search_str == "":
        servers = []
    else:
        query = {}
        terms = search_str.split(',')
        for items in terms:
            parsed = items.split('=')
            key = parsed[0].strip()
            value = parsed[1].strip()
            query[key] = value
        servers = Server.objects(__raw__=query)
    return render_template('search.html', servers=servers)


@bp.route('/automations', methods=['GET', 'POST'])
def automations():
    tasks = [
            ['reload_db', 'Refresh database'],
            ['custom_property_loader', 'Chef to SolarWinds custom properties'],
            ['vsphere_powerstates', 'vSphere Powerstates'],
            ['vsphere_old_new', 'vSphere servers with old/new postscript'],
            ['run_splitter', 'Attempt test run in split collections'],
            ['test', 'Test']
        ]
    if request.method == 'POST':
        try:
            search_str = request.form['search']
            return search(search_str)
        except BadRequestKeyError:
            pass
        try:
            selection = {
                'task': request.form['automations']
            }
            email_address = request.form['email-address']
            if email_address:
                selection['email'] = [email_address]
            else:
                selection['email'] = None

            if request.form['schedule'] == 'schedule':
                date = request.form['date-schedule']
                time = request.form['time-schedule']
                selection['schedule'] = parse(f"{date} {time}")
            result = manage_automations.run(selection)

        except BadRequestKeyError:
            pass
    return render_template('automations.html', title='Automations', tasks=tasks)

app/main/templates/_server.html
<table class="table">
	<tr>
		<td>
			<p><b>Tier:</b> {{ server.tier }}</p>
			<p><b>Environment:</b> {{ server.environment }}</p>
			<p><b>Department:</b> {{ server.department }}</p>
			<p><b>IPs</b> {{ server.ip }}</p>
			<p><b>Management Group:</b> {{ server.management_group }}</p>
			<p><b>Platform:</b> {{ server.platform }}</p>
			<p><b>Operating System:</b> {{ server.operating_system }}</p>
			<p><b>Power State:</b> {{ server.power_state }}</p>
			<p><b>Business Systems:</b>
				<ul>
					<p><b>Chef:</b> {{ server.business_system.chef }}</p>
					<p><b>vCenter:</b> {{server.business_system.vcenter }}</p>
					<p><b>SolarWinds:</b> {{ server.business_system.solarwinds }}</p>
					<p><b>ServiceNow:</b> {{ server.business_system.servicenow }}</p>
				</ul>
			</p>
			<p><b>UUIDs:</b> 
				<ul>
					<p><b>Chef GUUID:</b> {{server.uuids.chef_guuid }}</p>
					<p><b>SolarWinds URI:</b> {{server.uuids.solarwinds_uri }}</p>
					<p><b>vCenter:</b> 
						<ul>
							<p><b>MoRefID:</b> {{ server.uuids.vcenter.MoRefID }}</p>
							<p><b>InstanceUUID:</b> {{ server.uuids.vcenter.InstanceUuid }}</p>
							<p><b>SMBiosUUID:</b> {{ server.uuids.vcenter.SMBiosUuid }}</p>
						</ul>
					</p>
					<p><b>ServiceNow UUID::</b> {{server.uuids.servicenow_uuid }}</p>
				</ul>
			</p>
			<p><b>vCenter Tags:</b> 
			    <ul>
					{% for key, value in server.vcenter_tags.items() %}
					<dt><b>{{ key }}</b></dt>
					<dd>{{ value }}</dd>
					{% endfor %}
			    </ul>
			</p>
			<p><b>Chef Run List:</b>
				<ul>
					{% for item in server.chef_run_list %}
						<li>{{ item }}</li>
					{% endfor %}
			    </ul>
			</p>
			<p><b>Chef Tags:</b>
				<ul>
					{% for item in server.chef_tags %}
						<li>{{ item }}</li>
					{% endfor %}
			    </ul>
			</p>
		</td>
	</tr>
</table>

app/main/templates/automations.html
{% extends "base.html" %}

{% block app_content %}
	<div class="field-select">
		<h2 class="title-automations">Schedule Automation</h2>
		<form action="" method="post">
			<div class="task_container">
				<select name="automations" class="automation-selection selection">
					<option value="0">Select automation:</option>
					{% for task in tasks %}
					<option value='{{ task[0] }}'>{{ task[1] }}</option>
					{% endfor %}
				</select>

				<div id="email">
					<label for="email" class="email-text">Email(optional):</label>
					<input type="email" name="email-address" class="email-selection"  multiple placeholder="example1@delaware.gov, example2@delaware.gov">
				</div>

				<select name="schedule" class="schedule-selection" onchange="isScheduled(this);">
					<option value="now">Now</option>
					<option id ="schedule-option" value="schedule">Schedule</option>
				</select>

				<div id="schedule-select" class="datetime-selection" style="display:none;">
					<div class="date-selection">
						<label for="date" class="date-text">Date:</label>
						<input type="date" name="date-schedule" class="date-selection">
					</div>
					<div class="time-selection">
						<label for="time" class="time-text">Time:</label>
						<input type="time" name="time-schedule" class="time-selection">
					</div>
				</div>

				<button type="submit" class="selection"><i class="fa fa-superpowers" aria-hidden="true"></i></button>
			</div>
		</form>
	</div>
	<div class="flash-update">
		{% with messages = get_flashed_messages() %}
        {% if messages %}
            {% for message in messages %}
                {{ message }}
            {% endfor %}
        {% endif %}
        {% endwith %}
	</div>
{% endblock %}

app/main/templates/base.html
<!doctype html>

<html lang="en">
    <head>
        <meta charset="utf-8">
        {% if title %}
        <title>{{ title }} - Central SysOps</title>
        {% else %}
        <title>Welcome to Central SysOps</title>
        {% endif %}
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
        <link href="https://fonts.googleapis.com/css?family=Noto+Serif&display=swap" rel="stylesheet"> 
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <script src="{{ url_for('static', filename='js/scripts.js') }}"></script>
    </head>
    <body>
        <div class="page-container">
            <div class="content-wrap">
                <div class="main-nav">
                    <ul class="nav">
                        <li class="name">Central SysOps</li>
                        <li><a href="{{ url_for('main.index') }}">Home</a></li>
                        <li><a href="{{ url_for('main.automations') }}">Automations</a></li>
                    </ul>
                </div>
                        
                <header>
                    <form method="POST">
                        <div class="search-container">
                            <input type="text" placeholder="Search..." name="search">
                            <button type="submit"><i class="fa fa-search"></i></button>
                    </form>
                </header>
                <hr>
                <main>
                    {% block app_content %}{% endblock %}
                </main>
                <footer class="footer">
                    <p class="copyright">&copy;2019, DTI</p>
                </footer>
            </div>
        </div>
    </body>
</html>

app/main/templates/index.html
{% extends "base.html" %}

{% block app_content %}
	<h1 class="main-title">Welcome to Central SysOps!</h1>
{% endblock %}

app/main/templates/search.html
{% extends "base.html" %}

{% block app_content %}
		
		</style>
		<h1>Results: </h1>
		{% for server in servers %}
		<button class="accordion">{{ server.name }}</button>
		<div class="panel">
			{% include '_server.html' %}
		</div>
		{% endfor %}
		<script>serverAccordion();</script>
		
{% endblock %}